const EXERCISES = {
  bench_press:{id:'bench_press',name:'杠铃卧推',en:'Barbell Bench Press',sets:3,min:6,max:10,rir:'2',rest:180,increment:2.5,unit:'kg'},
  chest_supported_row:{id:'chest_supported_row',name:'胸托划船',en:'Chest Supported Row',sets:3,min:8,max:12,rir:'2',rest:120,increment:2.5,unit:'kg'},
  incline_db_press:{id:'incline_db_press',name:'上斜哑铃卧推',en:'Incline Dumbbell Press',sets:3,min:8,max:12,rir:'2',rest:120,increment:2.5,unit:'kg'},
  lat_pulldown:{id:'lat_pulldown',name:'高位下拉',en:'Lat Pulldown',sets:3,min:8,max:12,rir:'2',rest:120,increment:5,unit:'kg'},
  lateral_raise:{id:'lateral_raise',name:'侧平举',en:'Lateral Raise',sets:3,min:12,max:20,rir:'1–2',rest:75,increment:2,unit:'kg'},
  triceps_pushdown:{id:'triceps_pushdown',name:'绳索下压',en:'Triceps Pushdown',sets:2,min:10,max:15,rir:'1–2',rest:75,increment:2.5,unit:'kg'},
  biceps_curl:{id:'biceps_curl',name:'二头弯举',en:'Biceps Curl',sets:2,min:10,max:15,rir:'1–2',rest:75,increment:2,unit:'kg'},
  squat:{id:'squat',name:'杠铃深蹲 / 哈克深蹲',en:'Squat / Hack Squat',sets:3,min:6,max:10,rir:'2–3',rest:180,increment:5,unit:'kg'},
  leg_press:{id:'leg_press',name:'腿举',en:'Leg Press',sets:3,min:8,max:12,rir:'2',rest:120,increment:5,unit:'kg'},
  leg_curl:{id:'leg_curl',name:'腿弯举',en:'Leg Curl',sets:3,min:10,max:15,rir:'1–2',rest:90,increment:2.5,unit:'kg'},
  hip_thrust:{id:'hip_thrust',name:'臀推',en:'Hip Thrust',sets:3,min:8,max:12,rir:'2',rest:120,increment:5,unit:'kg'},
  calf_raise:{id:'calf_raise',name:'提踵',en:'Calf Raise',sets:3,min:10,max:15,rir:'1–2',rest:75,increment:5,unit:'kg'},
  cable_crunch:{id:'cable_crunch',name:'绳索卷腹',en:'Cable Crunch',sets:3,min:10,max:15,rir:'1–2',rest:75,increment:2.5,unit:'kg'},
  overhead_press:{id:'overhead_press',name:'肩推',en:'Overhead Press',sets:3,min:6,max:10,rir:'2',rest:150,increment:2.5,unit:'kg'},
  pull_up:{id:'pull_up',name:'引体向上 / 高位下拉',en:'Pull-up / Pulldown',sets:3,min:6,max:10,rir:'2',rest:150,increment:2.5,unit:'kg'},
  cable_row:{id:'cable_row',name:'坐姿绳索划船',en:'Seated Cable Row',sets:3,min:8,max:12,rir:'2',rest:120,increment:5,unit:'kg'},
  bulgarian:{id:'bulgarian',name:'保加利亚分腿蹲',en:'Bulgarian Split Squat',sets:3,min:8,max:12,rir:'2',rest:120,increment:2.5,unit:'kg'},
  back_extension:{id:'back_extension',name:'45°山羊挺身',en:'45° Back Extension',sets:3,min:10,max:15,rir:'2',rest:90,increment:2.5,unit:'kg'},
  hanging_leg_raise:{id:'hanging_leg_raise',name:'悬垂举腿 / 卷腹',en:'Hanging Leg Raise',sets:3,min:10,max:15,rir:'1–2',rest:75,increment:0,unit:'次'}
};
const WORKOUTS = {
  upper_a:{id:'upper_a',name:'Upper A',focus:'卧推重点',duration:'75 min',exercises:['bench_press','chest_supported_row','incline_db_press','lat_pulldown','lateral_raise','triceps_pushdown','biceps_curl']},
  lower_a:{id:'lower_a',name:'Lower A',focus:'蹲举重点',duration:'70 min',exercises:['squat','leg_press','leg_curl','hip_thrust','calf_raise','cable_crunch']},
  upper_b:{id:'upper_b',name:'Upper B',focus:'肩推重点',duration:'70 min',exercises:['overhead_press','pull_up','bench_press','cable_row','lateral_raise','biceps_curl','triceps_pushdown']},
  lower_b:{id:'lower_b',name:'Lower B',focus:'单腿与后链',duration:'65 min',exercises:['squat','bulgarian','leg_curl','back_extension','calf_raise','hanging_leg_raise']}
};
const WORKOUT_ORDER = ['upper_a','lower_a','upper_b','lower_b'];
const PHASES = [{from:1,to:2,name:'建立基准',short:'BASELINE PHASE',desc:'找到合适重量，保持 RIR 3。'},{from:3,to:6,name:'第一积累期',short:'BUILD PHASE',desc:'增加次数与重量，保持动作质量。'},{from:7,to:7,name:'减载周',short:'DELOAD',desc:'训练量减半，RIR 4–5。'},{from:8,to:13,name:'第二积累期',short:'BUILD PHASE',desc:'稳步推进，积累训练容量。'},{from:14,to:14,name:'减载周',short:'DELOAD',desc:'恢复身体，为力量期做准备。'},{from:15,to:20,name:'力量偏重期',short:'STRENGTH PHASE',desc:'更高强度，更长休息。'},{from:21,to:21,name:'减载周',short:'DELOAD',desc:'训练量减半，保持动作。'},{from:22,to:25,name:'最终积累',short:'FINAL BUILD',desc:'完成最后一轮渐进超负荷。'},{from:26,to:26,name:'评估周',short:'ASSESSMENT',desc:'复盘半年变化，设定下一周期。'}];
const key = 'training-recomp-v1';
const defaultState = {week:3,weekSessionCount:0,nextWorkoutIndex:0,bodyLogs:[{date:'09/20',weight:60.2,waist:78.5},{date:'09/21',weight:60.0,waist:78.2},{date:'09/22',weight:59.9,waist:78.0},{date:'09/23',weight:59.8,waist:77.8},{date:'09/24',weight:59.9,waist:77.7},{date:'09/25',weight:59.8,waist:77.5}],workoutLogs:[],sessions:[],restLogs:[],completedWorkouts:[],habits:{}};
let state = loadState();
let currentWorkoutId = getNextWorkout().id;
let session = null;
let timerInterval = null;
let workoutStart = null;

function loadState(){try{const saved=JSON.parse(localStorage.getItem(key)||'{}');const merged={...defaultState,...saved};if(!Array.isArray(merged.sessions)){merged.sessions=(merged.workoutLogs||[]).map((log,index)=>({date:log.date,workout:log.workout,sequence:index+1,week:merged.week||3}))}if(!Array.isArray(merged.restLogs))merged.restLogs=[];if(typeof merged.nextWorkoutIndex!=='number')merged.nextWorkoutIndex=merged.sessions.length%WORKOUT_ORDER.length;if(typeof merged.weekSessionCount!=='number')merged.weekSessionCount=merged.sessions.filter(s=>s.week===merged.week).length%4;return merged}catch{return {...defaultState}}}
function saveState(){localStorage.setItem(key,JSON.stringify(state))}
function qs(selector){return document.querySelector(selector)}
function isoDate(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
function formatDate(){const d=new Date();return `${String(d.getMonth()+1).padStart(2,'0')}/${String(d.getDate()).padStart(2,'0')}`}
function formatSessionDate(date){if(!date)return '';const [y,m,d]=date.split('-');return `${m}/${d}`}
function getNextWorkout(){return WORKOUTS[WORKOUT_ORDER[state.nextWorkoutIndex%WORKOUT_ORDER.length]]}
function getSessionCount(){return Array.isArray(state.sessions)?state.sessions.length:state.workoutLogs.length}
function getPhase(){return PHASES.find(p=>state.week>=p.from&&state.week<=p.to)||PHASES[1]}
function getLastLog(exerciseId,workoutId=currentWorkoutId){return [...state.workoutLogs].reverse().find(log=>log.workout===workoutId&&log.exercises?.some(e=>e.exercise===exerciseId))?.exercises.find(e=>e.exercise===exerciseId)}
function recommendation(exercise,last){const base=last?.sets?.[0]?.weight||suggestedBase(exercise.id);if(!last)return {weight:base,text:`建议从 ${base} kg 开始`};const reps=last.sets.map(s=>Number(s.reps)||0);const allTop=reps.length>=exercise.sets&&reps.every(r=>r>=exercise.max);const total=reps.reduce((a,b)=>a+b,0);if(allTop&&exercise.increment>0)return {weight:roundWeight(base+exercise.increment),text:`上次已达上限，建议加重至 ${roundWeight(base+exercise.increment)} kg`};return {weight:base,text:`继续 ${base} kg · 下次目标总次数 ≥ ${total+1}`}}
function suggestedBase(id){const map={bench_press:35,overhead_press:20,squat:50,leg_press:80,lat_pulldown:35,chest_supported_row:35,incline_db_press:15,lateral_raise:7.5,triceps_pushdown:20,biceps_curl:10,leg_curl:30,hip_thrust:50,calf_raise:40,cable_crunch:20,cable_row:35,pull_up:0,bulgarian:10,back_extension:10,hanging_leg_raise:0};return map[id]??20}
function roundWeight(n){return Math.round(n*2)/2}
function phaseIsDeload(){return getPhase().short==='DELOAD'}
function effectiveExercise(ex){if(!phaseIsDeload())return ex;return {...ex,sets:Math.max(1,Math.ceil(ex.sets/2)),min:Math.max(5,ex.min-2),max:Math.max(6,ex.max-2),rir:'4–5'}}

function init(){
  const phase=getPhase();
  qs('#current-week').textContent=state.week;qs('#week-progress').textContent=`${Math.round(state.week/26*100)}%`;qs('.week-ring').style.background=`conic-gradient(var(--lime) 0 ${state.week/26*100}%,#2b3530 ${state.week/26*100}% 100%)`;
  qs('#phase-label').textContent=`${phase.name} · ${phase.short}`;qs('#today-date').textContent=formatDate();
  renderHome();renderPlan();renderProgress();bindNavigation();bindModal();
  if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
}
function renderHome(){
  const phase=getPhase();qs('#current-week').textContent=state.week;qs('#week-progress').textContent=`${Math.round(state.week/26*100)}%`;qs('.week-ring').style.background=`conic-gradient(var(--lime) 0 ${state.week/26*100}%,#2b3530 ${state.week/26*100}% 100%)`;qs('#phase-label').textContent=`${phase.name} · ${phase.short}`;
  const next=getNextWorkout();currentWorkoutId=next.id;qs('#today-name').textContent=next.name;qs('#today-focus').textContent=`${next.focus} · ${next.exercises.length} 个动作`;qs('#today-card .today-meta').innerHTML=`<span>约 ${next.duration.replace(' min','')} min</span><span>RIR ${phaseIsDeload()?'4–5':'2'}</span>`;
  const latest=state.bodyLogs.at(-1);if(latest)qs('#home-weight').innerHTML=`${latest.weight.toFixed(1)} <i>kg</i>`;
  qs('#start-today').innerHTML=`开始下一次训练 <span>→</span>`;qs('#start-today').onclick=()=>openWorkout(next.id);
  const sessionsThisWeek=state.sessions.filter(s=>s.week===state.week).length;qs('#week-done-count').textContent=`${sessionsThisWeek} / 4 次完成`;
  const recent=state.sessions.slice(-4).reverse();const list=qs('#schedule-list');list.innerHTML=recent.length?recent.map(s=>{const w=WORKOUTS[s.workout];return `<div class="schedule-row done"><span class="day">${formatSessionDate(s.date)}</span><span class="workout">${w.name}<small class="focus">${w.focus} · 第 ${s.sequence} 次</small></span><span class="status">✓</span></div>`}).join(''):`<div class="schedule-row next"><span class="day">NEXT</span><span class="workout">${next.name}<small class="focus">完成后自动进入下一项</small></span><span class="status">→</span></div>`;
  qs('#workout-choices').innerHTML=WORKOUT_ORDER.map(id=>{const w=WORKOUTS[id];return `<button class="choice-btn ${id===next.id?'next-choice':''}" data-choice="${id}"><strong>${w.name}</strong><small>${w.focus}</small></button>`}).join('');qs('#workout-choices').querySelectorAll('[data-choice]').forEach(btn=>btn.onclick=()=>openWorkout(btn.dataset.choice));qs('#rest-today').onclick=markRestToday;
  const last=getLastLog('bench_press','upper_a');const rec=recommendation(EXERCISES.bench_press,last);qs('#next-step').textContent=last?`卧推 · ${rec.text}`:`完成第一次训练后，这里会告诉你下一次的建议重量。`;
}
function openWorkout(workoutId){currentWorkoutId=workoutId;session={};workoutStart=Date.now();renderWorkout();switchView('workout')}
function renderWorkout(){const workout=WORKOUTS[currentWorkoutId];qs('#workout-title').textContent=workout.name;qs('#workout-subtitle').textContent=`${workout.focus} · Week ${state.week}`;session=session||{};const list=qs('#exercise-list');list.innerHTML=workout.exercises.map(id=>renderExercise(EXERCISES[id])).join('');updateWorkoutProgress();}
function renderExercise(raw){const ex=effectiveExercise(raw),last=getLastLog(raw.id),rec=recommendation(raw,last),saved=session[raw.id]||Array.from({length:ex.sets},()=>({weight:rec.weight,reps:last?.sets?.[0]?.reps||'',rir:raw.rir,done:false}));session[raw.id]=saved;const allDone=saved.every(s=>s.done);return `<article class="exercise-card ${allDone?'completed':''}" data-exercise="${raw.id}"><div class="exercise-top"><div class="exercise-title"><h2>${raw.name}</h2><p>${raw.en}</p></div><span class="exercise-tag">${ex.sets} × ${ex.min}–${ex.max}</span></div><div class="exercise-details"><span>目标 <strong>${ex.sets} × ${ex.min}–${ex.max}</strong></span><span>RIR <strong>${ex.rir}</strong></span><span>休息 <strong>${ex.rest}s</strong></span></div>${last?`<div class="last-performance"><span>上次 · ${last.sets.map(s=>s.reps||'–').join(' / ')}</span><strong>${last.sets[0]?.weight||rec.weight} kg</strong></div>`:''}<div class="recommendation"><span>RECOMMENDED</span><strong>${rec.text}</strong></div><div class="set-head"><span>SET</span><span>WEIGHT</span><span>REPS</span><span>RIR</span><span></span></div><div class="sets-table">${saved.map((set,i)=>`<div class="set-row ${set.done?'done':''}" data-set="${i}"><span>${i+1}</span><input data-field="weight" type="number" step="0.5" value="${set.weight??''}" aria-label="重量"><input data-field="reps" type="number" min="0" value="${set.reps??''}" aria-label="次数"><input data-field="rir" type="number" min="0" max="5" value="${set.rir??''}" aria-label="RIR"><button class="set-done" aria-label="完成第 ${i+1} 组">${set.done?'✓':'○'}</button></div>`).join('')}</div><div class="rest-hint">每组完成后点击 <b>○</b>，自动开始休息计时</div></article>`}
function bindWorkoutEvents(){qs('#exercise-list').querySelectorAll('.exercise-card').forEach(card=>{const id=card.dataset.exercise;card.querySelectorAll('input').forEach(input=>input.addEventListener('input',()=>{const row=input.closest('.set-row');const i=Number(row.dataset.set);session[id][i][input.dataset.field]=input.value;saveState()}));card.querySelectorAll('.set-done').forEach(btn=>btn.addEventListener('click',()=>{const row=btn.closest('.set-row');const i=Number(row.dataset.set);session[id][i].done=!session[id][i].done;if(session[id][i].done){startRest(EXERCISES[id].rest);showToast('已记录，开始休息');}renderWorkout();bindWorkoutEvents();}));});}
function updateWorkoutProgress(){const workout=WORKOUTS[currentWorkoutId];let complete=0;workout.exercises.forEach(id=>{if(session?.[id]?.length&&session[id].every(s=>s.done))complete++});qs('#exercise-progress-text').textContent=`${complete} / ${workout.exercises.length} 动作`;qs('#exercise-progress-bar').style.width=`${complete/workout.exercises.length*100}%`;if(workoutStart){const sec=Math.floor((Date.now()-workoutStart)/1000);qs('#workout-elapsed').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}}
function finishWorkout(){const workout=WORKOUTS[currentWorkoutId];const exercises=workout.exercises.map(id=>({exercise:id,sets:(session[id]||[]).map(s=>({weight:Number(s.weight)||0,reps:Number(s.reps)||0,rir:Number(s.rir)||0}))})).filter(e=>e.sets.some(s=>s.reps>0));if(!exercises.length){showToast('先记录至少一组训练');return}const date=isoDate();const sequence=getSessionCount()+1;const log={date,workout:currentWorkoutId,exercises};state.workoutLogs.push(log);state.sessions.push({date,workout:currentWorkoutId,sequence,week:state.week});state.nextWorkoutIndex=(WORKOUT_ORDER.indexOf(currentWorkoutId)+1)%WORKOUT_ORDER.length;state.weekSessionCount=(state.weekSessionCount||0)+1;if(state.weekSessionCount>=4&&state.week<26){state.week+=1;state.weekSessionCount=0}saveState();showToast('训练已保存 · 下一项已安排');renderHome();renderPlan();setTimeout(()=>switchView('home'),700)}
function markRestToday(){const date=isoDate();if(!state.restLogs.some(log=>log.date===date))state.restLogs.push({date});saveState();renderHome();renderPlan();showToast('已记录今天休息，下一项训练保留')}
function startRest(seconds){clearInterval(timerInterval);let remaining=seconds;qs('#rest-timer').hidden=false;const tick=()=>{qs('#timer-display').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;if(remaining<=0){clearInterval(timerInterval);showToast('休息结束，准备下一组');qs('#rest-timer').hidden=true}remaining--};tick();timerInterval=setInterval(tick,1000)}
function renderProgress(){const logs=state.bodyLogs;const weight=logs.at(-1)?.weight||60;qs('#chart-value').innerHTML=`${weight.toFixed(1)} <i>kg</i>`;renderChart('weight');renderStrength();}
function renderChart(metric){const logs=state.bodyLogs;const values=logs.length?logs.map(l=>metric==='waist'?l.waist:l.weight):[60];const min=Math.min(...values),max=Math.max(...values),range=max-min||1;qs('#progress-chart').innerHTML=values.map(v=>`<span class="chart-bar" style="height:${22+(v-min)/range*70}%" title="${v}"></span>`).join('');qs('#chart-labels').innerHTML=values.map((_,i)=>`<span>${logs[i]?.date||''}</span>`).join('');if(metric==='waist'){qs('#chart-kicker').textContent='WAIST TREND';qs('#chart-value').innerHTML=`${values.at(-1).toFixed(1)} <i>cm</i>`;qs('#trend-badge').textContent=values.at(-1)<=values[0]?'下降':'观察';}else{qs('#chart-kicker').textContent='7-DAY AVERAGE';qs('#chart-value').innerHTML=`${values.at(-1).toFixed(1)} <i>kg</i>`;qs('#trend-badge').textContent='稳定'}}
function renderStrength(){const ids=['bench_press','overhead_press','squat','lat_pulldown','chest_supported_row'];qs('#strength-list').innerHTML=ids.map(id=>{const ex=EXERCISES[id],logs=state.workoutLogs.flatMap(l=>l.exercises||[]).filter(e=>e.exercise===id),last=logs.at(-1);return `<div class="strength-row"><div class="name">${ex.name}<small>${last?'最近训练':'等待第一次记录'}</small></div><strong>${last?`${last.sets[0].weight} kg × ${last.sets[0].reps}`:'—'}</strong></div>`}).join('')}
function saveBodyLog(){const weight=Number(qs('#weight-input').value),waist=Number(qs('#waist-input').value);if(!weight&&!waist){showToast('请输入体重或腰围');return}const prev=state.bodyLogs.at(-1)||{};state.bodyLogs.push({date:formatDate(),weight:weight||prev.weight||60,waist:waist||prev.waist||78});saveState();qs('#weight-input').value='';qs('#waist-input').value='';renderProgress();renderHome();showToast('身体数据已保存')}
function phaseForWeek(week){return PHASES.find(p=>week>=p.from&&week<=p.to)||PHASES[1]}
function phaseClass(phase){if(phase.short==='DELOAD')return 'deload';if(phase.short==='STRENGTH PHASE')return 'strength';if(phase.short==='ASSESSMENT')return 'assessment';return 'build'}
function renderActivityCalendar(){const now=new Date(),year=now.getFullYear(),month=now.getMonth(),firstDay=(new Date(year,month,1).getDay()+6)%7,days=new Date(year,month+1,0).getDate();qs('#activity-month-label').textContent=`${year}.${String(month+1).padStart(2,'0')}`;let html=Array.from({length:firstDay},()=>'<div class="month-day empty"></div>').join('');for(let day=1;day<=days;day++){const date=isoDate(new Date(year,month,day)),sessionLog=state.sessions.find(s=>s.date===date),rest=state.restLogs.some(s=>s.date===date),today=date===isoDate();const mark=sessionLog?WORKOUTS[sessionLog.workout].name:rest?'REST':'';html+=`<div class="month-day ${sessionLog?'workout-day':''} ${rest&&!sessionLog?'rest-day':''} ${today?'today':''}"><span class="date-number">${day}</span>${mark?`<span class="day-mark">${mark}</span>`:''}</div>`}qs('#activity-calendar').innerHTML=html}
function renderPlan(){const phase=getPhase();qs('#plan-phase-name').textContent=phase.name;qs('#plan-phase-desc').textContent=phase.desc;qs('#plan-week-big').innerHTML=`${String(state.week).padStart(2,'0')}<span>/26</span>`;qs('#calendar-current-label').textContent=`当前 · W${String(state.week).padStart(2,'0')}`;qs('#phase-calendar').innerHTML=Array.from({length:26},(_,i)=>{const week=i+1,p=phaseForWeek(week),current=week===state.week;const focus=p.short==='DELOAD'?'恢复':p.short==='STRENGTH PHASE'?'强度':p.short==='ASSESSMENT'?'评估':'渐进';return `<div class="week-cell ${phaseClass(p)} ${current?'current':''}" aria-label="第 ${week} 周 · ${p.name}"><span class="week-num">W${String(week).padStart(2,'0')}</span><span class="week-phase">${p.name}</span><span class="week-focus">${focus}</span></div>`}).join('');renderActivityCalendar();qs('#timeline').innerHTML=PHASES.map(p=>`<div class="phase-row ${state.week>=p.from&&state.week<=p.to?'current':''}"><span class="phase-dot"></span><div><div class="phase-name">${p.name}</div><div class="phase-desc">${p.desc}</div></div><span class="phase-weeks">W${p.from}${p.to!==p.from?`–${p.to}`:''}</span></div>`).join('');qs('#habit-row').querySelectorAll('button').forEach(btn=>{const checked=state.habits[btn.dataset.habit];btn.classList.toggle('checked',!!checked);btn.textContent=`${checked?'●':'○'} ${btn.textContent.slice(2)}`})}
function bindNavigation(){document.querySelectorAll('[data-nav]').forEach(btn=>btn.addEventListener('click',()=>switchView(btn.dataset.nav)));qs('#finish-workout').addEventListener('click',finishWorkout);qs('#save-body-log').addEventListener('click',saveBodyLog);qs('#add-time').addEventListener('click',()=>{const el=qs('#timer-display');const [m,s]=el.textContent.split(':').map(Number);startRest(m*60+s+30)});qs('#skip-time').addEventListener('click',()=>{clearInterval(timerInterval);qs('#rest-timer').hidden=true});document.querySelectorAll('.metric-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.metric-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');renderChart(btn.dataset.metric)}));qs('#habit-row').addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;state.habits[btn.dataset.habit]=!state.habits[btn.dataset.habit];saveState();renderPlan()});}
function switchView(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.nav===view));if(view==='workout'){renderWorkout();bindWorkoutEvents()}if(view==='progress')renderProgress();if(view==='plan')renderPlan();window.scrollTo({top:0,behavior:'smooth'})}
function bindModal(){const back=qs('#modal-backdrop');qs('#rir-help').addEventListener('click',()=>back.hidden=false);qs('#modal-close').addEventListener('click',()=>back.hidden=true);back.addEventListener('click',e=>{if(e.target===back)back.hidden=true});const resetBack=qs('#reset-backdrop');qs('#reset-plan').addEventListener('click',()=>resetBack.hidden=false);qs('#reset-close').addEventListener('click',()=>resetBack.hidden=true);qs('#reset-cancel').addEventListener('click',()=>resetBack.hidden=true);resetBack.addEventListener('click',e=>{if(e.target===resetBack)resetBack.hidden=true});qs('#reset-confirm').addEventListener('click',()=>resetTrainingPlan(resetBack))}
function resetTrainingPlan(backdrop){state.week=1;state.weekSessionCount=0;state.nextWorkoutIndex=0;state.sessions=[];state.workoutLogs=[];state.restLogs=[];state.completedWorkouts=[];currentWorkoutId=WORKOUT_ORDER[0];session=null;saveState();backdrop.hidden=true;renderHome();renderProgress();renderPlan();showToast('训练计划已重置 · 从 Week 1 开始');switchView('plan')}
let toastTimeout;function showToast(message){const t=qs('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>t.classList.remove('show'),2400)}
init();
